//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.26 at 12:07:36 AM MDT 
//


package collada.org.collada._2008._03.colladaschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 			This element allows for connecting components, such as rigid_body into complex physics models 
 * 			with moveable parts.
 * 			
 * 
 * <p>Java class for rigid_constraint_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rigid_constraint_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ref_attachment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="translate" type="{http://www.collada.org/2008/03/COLLADASchema}translate_type"/>
 *                     &lt;element name="rotate" type="{http://www.collada.org/2008/03/COLLADASchema}rotate_type"/>
 *                   &lt;/choice>
 *                   &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="rigid_body" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attachment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="translate" type="{http://www.collada.org/2008/03/COLLADASchema}translate_type"/>
 *                     &lt;element name="rotate" type="{http://www.collada.org/2008/03/COLLADASchema}rotate_type"/>
 *                   &lt;/choice>
 *                   &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="rigid_body" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="technique_common">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="enabled" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                           &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="interpenetrate" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                           &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="limits" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="swing_cone_and_twist" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="min" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
 *                                       &lt;element name="max" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="linear" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="min" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
 *                                       &lt;element name="max" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="spring" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="angular" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="stiffness" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
 *                                       &lt;element name="damping" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
 *                                       &lt;element name="target_value" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="linear" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="stiffness" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
 *                                       &lt;element name="damping" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
 *                                       &lt;element name="target_value" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="technique" type="{http://www.collada.org/2008/03/COLLADASchema}technique_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sid" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rigid_constraint_type", propOrder = {
    "refAttachment",
    "attachment",
    "techniqueCommon",
    "techniques",
    "extras"
})
public class RigidConstraintType {

    @XmlElement(name = "ref_attachment", required = true)
    protected RefAttachment refAttachment;
    @XmlElement(required = true)
    protected Attachment attachment;
    @XmlElement(name = "technique_common", required = true)
    protected TechniqueCommon techniqueCommon;
    @XmlElement(name = "technique")
    protected List<TechniqueType> techniques;
    @XmlElement(name = "extra")
    protected List<ExtraType> extras;
    @XmlAttribute(name = "sid", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sid;
    @XmlAttribute(name = "name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;

    /**
     * Gets the value of the refAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.RefAttachment }
     *     
     */
    public RefAttachment getRefAttachment() {
        return refAttachment;
    }

    /**
     * Sets the value of the refAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.RefAttachment }
     *     
     */
    public void setRefAttachment(RefAttachment value) {
        this.refAttachment = value;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * @return
     *     possible object is
     *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.Attachment }
     *     
     */
    public Attachment getAttachment() {
        return attachment;
    }

    /**
     * Sets the value of the attachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.Attachment }
     *     
     */
    public void setAttachment(Attachment value) {
        this.attachment = value;
    }

    /**
     * Gets the value of the techniqueCommon property.
     * 
     * @return
     *     possible object is
     *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon }
     *     
     */
    public TechniqueCommon getTechniqueCommon() {
        return techniqueCommon;
    }

    /**
     * Sets the value of the techniqueCommon property.
     * 
     * @param value
     *     allowed object is
     *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon }
     *     
     */
    public void setTechniqueCommon(TechniqueCommon value) {
        this.techniqueCommon = value;
    }

    /**
     * Gets the value of the techniques property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the techniques property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechniques().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TechniqueType }
     * 
     * 
     */
    public List<TechniqueType> getTechniques() {
        if (techniques == null) {
            techniques = new ArrayList<TechniqueType>();
        }
        return this.techniques;
    }

    /**
     * Gets the value of the extras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtraType }
     * 
     * 
     */
    public List<ExtraType> getExtras() {
        if (extras == null) {
            extras = new ArrayList<ExtraType>();
        }
        return this.extras;
    }

    /**
     * Gets the value of the sid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSid() {
        return sid;
    }

    /**
     * Sets the value of the sid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSid(String value) {
        this.sid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="translate" type="{http://www.collada.org/2008/03/COLLADASchema}translate_type"/>
     *           &lt;element name="rotate" type="{http://www.collada.org/2008/03/COLLADASchema}rotate_type"/>
     *         &lt;/choice>
     *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="rigid_body" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "translatesAndRotates",
        "extras"
    })
    public static class Attachment {

        @XmlElements({
            @XmlElement(name = "translate", type = TranslateType.class),
            @XmlElement(name = "rotate", type = RotateType.class)
        })
        protected List<Object> translatesAndRotates;
        @XmlElement(name = "extra")
        protected List<ExtraType> extras;
        @XmlAttribute(name = "rigid_body")
        @XmlSchemaType(name = "anyURI")
        protected String rigidBody;

        /**
         * Gets the value of the translatesAndRotates property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the translatesAndRotates property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTranslatesAndRotates().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TranslateType }
         * {@link RotateType }
         * 
         * 
         */
        public List<Object> getTranslatesAndRotates() {
            if (translatesAndRotates == null) {
                translatesAndRotates = new ArrayList<Object>();
            }
            return this.translatesAndRotates;
        }

        /**
         * Gets the value of the extras property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extras property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtras().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExtraType }
         * 
         * 
         */
        public List<ExtraType> getExtras() {
            if (extras == null) {
                extras = new ArrayList<ExtraType>();
            }
            return this.extras;
        }

        /**
         * Gets the value of the rigidBody property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRigidBody() {
            return rigidBody;
        }

        /**
         * Sets the value of the rigidBody property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRigidBody(String value) {
            this.rigidBody = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="translate" type="{http://www.collada.org/2008/03/COLLADASchema}translate_type"/>
     *           &lt;element name="rotate" type="{http://www.collada.org/2008/03/COLLADASchema}rotate_type"/>
     *         &lt;/choice>
     *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="rigid_body" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "translatesAndRotates",
        "extras"
    })
    public static class RefAttachment {

        @XmlElements({
            @XmlElement(name = "translate", type = TranslateType.class),
            @XmlElement(name = "rotate", type = RotateType.class)
        })
        protected List<Object> translatesAndRotates;
        @XmlElement(name = "extra")
        protected List<ExtraType> extras;
        @XmlAttribute(name = "rigid_body")
        @XmlSchemaType(name = "anyURI")
        protected String rigidBody;

        /**
         * Gets the value of the translatesAndRotates property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the translatesAndRotates property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTranslatesAndRotates().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TranslateType }
         * {@link RotateType }
         * 
         * 
         */
        public List<Object> getTranslatesAndRotates() {
            if (translatesAndRotates == null) {
                translatesAndRotates = new ArrayList<Object>();
            }
            return this.translatesAndRotates;
        }

        /**
         * Gets the value of the extras property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extras property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtras().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExtraType }
         * 
         * 
         */
        public List<ExtraType> getExtras() {
            if (extras == null) {
                extras = new ArrayList<ExtraType>();
            }
            return this.extras;
        }

        /**
         * Gets the value of the rigidBody property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRigidBody() {
            return rigidBody;
        }

        /**
         * Sets the value of the rigidBody property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRigidBody(String value) {
            this.rigidBody = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="enabled" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *                 &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="interpenetrate" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *                 &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="limits" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="swing_cone_and_twist" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="min" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
     *                             &lt;element name="max" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="linear" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="min" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
     *                             &lt;element name="max" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="spring" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="angular" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="stiffness" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
     *                             &lt;element name="damping" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
     *                             &lt;element name="target_value" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="linear" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="stiffness" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
     *                             &lt;element name="damping" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
     *                             &lt;element name="target_value" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enabled",
        "interpenetrate",
        "limits",
        "spring"
    })
    public static class TechniqueCommon {

        @XmlElement(defaultValue = "true")
        protected Enabled enabled;
        @XmlElement(defaultValue = "false")
        protected Interpenetrate interpenetrate;
        protected Limits limits;
        protected Spring spring;

        /**
         * Gets the value of the enabled property.
         * 
         * @return
         *     possible object is
         *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Enabled }
         *     
         */
        public Enabled getEnabled() {
            return enabled;
        }

        /**
         * Sets the value of the enabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Enabled }
         *     
         */
        public void setEnabled(Enabled value) {
            this.enabled = value;
        }

        /**
         * Gets the value of the interpenetrate property.
         * 
         * @return
         *     possible object is
         *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Interpenetrate }
         *     
         */
        public Interpenetrate getInterpenetrate() {
            return interpenetrate;
        }

        /**
         * Sets the value of the interpenetrate property.
         * 
         * @param value
         *     allowed object is
         *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Interpenetrate }
         *     
         */
        public void setInterpenetrate(Interpenetrate value) {
            this.interpenetrate = value;
        }

        /**
         * Gets the value of the limits property.
         * 
         * @return
         *     possible object is
         *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Limits }
         *     
         */
        public Limits getLimits() {
            return limits;
        }

        /**
         * Sets the value of the limits property.
         * 
         * @param value
         *     allowed object is
         *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Limits }
         *     
         */
        public void setLimits(Limits value) {
            this.limits = value;
        }

        /**
         * Gets the value of the spring property.
         * 
         * @return
         *     possible object is
         *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Spring }
         *     
         */
        public Spring getSpring() {
            return spring;
        }

        /**
         * Sets the value of the spring property.
         * 
         * @param value
         *     allowed object is
         *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Spring }
         *     
         */
        public void setSpring(Spring value) {
            this.spring = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
         *       &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Enabled {

            @XmlValue
            protected boolean value;
            @XmlAttribute(name = "sid")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String sid;

            /**
             * Gets the value of the value property.
             * 
             */
            public boolean isValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(boolean value) {
                this.value = value;
            }

            /**
             * Gets the value of the sid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSid() {
                return sid;
            }

            /**
             * Sets the value of the sid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSid(String value) {
                this.sid = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
         *       &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Interpenetrate {

            @XmlValue
            protected boolean value;
            @XmlAttribute(name = "sid")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String sid;

            /**
             * Gets the value of the value property.
             * 
             */
            public boolean isValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(boolean value) {
                this.value = value;
            }

            /**
             * Gets the value of the sid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSid() {
                return sid;
            }

            /**
             * Sets the value of the sid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSid(String value) {
                this.sid = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="swing_cone_and_twist" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="min" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
         *                   &lt;element name="max" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="linear" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="min" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
         *                   &lt;element name="max" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "swingConeAndTwist",
            "linear"
        })
        public static class Limits {

            @XmlElement(name = "swing_cone_and_twist")
            protected SwingConeAndTwist swingConeAndTwist;
            protected Linear linear;

            /**
             * Gets the value of the swingConeAndTwist property.
             * 
             * @return
             *     possible object is
             *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Limits.SwingConeAndTwist }
             *     
             */
            public SwingConeAndTwist getSwingConeAndTwist() {
                return swingConeAndTwist;
            }

            /**
             * Sets the value of the swingConeAndTwist property.
             * 
             * @param value
             *     allowed object is
             *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Limits.SwingConeAndTwist }
             *     
             */
            public void setSwingConeAndTwist(SwingConeAndTwist value) {
                this.swingConeAndTwist = value;
            }

            /**
             * Gets the value of the linear property.
             * 
             * @return
             *     possible object is
             *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Limits.Linear }
             *     
             */
            public Linear getLinear() {
                return linear;
            }

            /**
             * Sets the value of the linear property.
             * 
             * @param value
             *     allowed object is
             *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Limits.Linear }
             *     
             */
            public void setLinear(Linear value) {
                this.linear = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="min" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
             *         &lt;element name="max" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "min",
                "max"
            })
            public static class Linear {

                @XmlElement(defaultValue = "0.0 0.0 0.0")
                protected TargetableFloat3Type min;
                @XmlElement(defaultValue = "0.0 0.0 0.0")
                protected TargetableFloat3Type max;

                /**
                 * Gets the value of the min property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloat3Type }
                 *     
                 */
                public TargetableFloat3Type getMin() {
                    return min;
                }

                /**
                 * Sets the value of the min property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloat3Type }
                 *     
                 */
                public void setMin(TargetableFloat3Type value) {
                    this.min = value;
                }

                /**
                 * Gets the value of the max property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloat3Type }
                 *     
                 */
                public TargetableFloat3Type getMax() {
                    return max;
                }

                /**
                 * Sets the value of the max property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloat3Type }
                 *     
                 */
                public void setMax(TargetableFloat3Type value) {
                    this.max = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="min" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
             *         &lt;element name="max" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "min",
                "max"
            })
            public static class SwingConeAndTwist {

                @XmlElement(defaultValue = "0.0 0.0 0.0")
                protected TargetableFloat3Type min;
                @XmlElement(defaultValue = "0.0 0.0 0.0")
                protected TargetableFloat3Type max;

                /**
                 * Gets the value of the min property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloat3Type }
                 *     
                 */
                public TargetableFloat3Type getMin() {
                    return min;
                }

                /**
                 * Sets the value of the min property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloat3Type }
                 *     
                 */
                public void setMin(TargetableFloat3Type value) {
                    this.min = value;
                }

                /**
                 * Gets the value of the max property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloat3Type }
                 *     
                 */
                public TargetableFloat3Type getMax() {
                    return max;
                }

                /**
                 * Sets the value of the max property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloat3Type }
                 *     
                 */
                public void setMax(TargetableFloat3Type value) {
                    this.max = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="angular" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="stiffness" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
         *                   &lt;element name="damping" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
         *                   &lt;element name="target_value" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="linear" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="stiffness" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
         *                   &lt;element name="damping" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
         *                   &lt;element name="target_value" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "angular",
            "linear"
        })
        public static class Spring {

            protected Angular angular;
            protected Linear linear;

            /**
             * Gets the value of the angular property.
             * 
             * @return
             *     possible object is
             *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Spring.Angular }
             *     
             */
            public Angular getAngular() {
                return angular;
            }

            /**
             * Sets the value of the angular property.
             * 
             * @param value
             *     allowed object is
             *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Spring.Angular }
             *     
             */
            public void setAngular(Angular value) {
                this.angular = value;
            }

            /**
             * Gets the value of the linear property.
             * 
             * @return
             *     possible object is
             *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Spring.Linear }
             *     
             */
            public Linear getLinear() {
                return linear;
            }

            /**
             * Sets the value of the linear property.
             * 
             * @param value
             *     allowed object is
             *     {@link collada.org.collada._2008._03.colladaschema.RigidConstraintType.TechniqueCommon.Spring.Linear }
             *     
             */
            public void setLinear(Linear value) {
                this.linear = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="stiffness" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
             *         &lt;element name="damping" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
             *         &lt;element name="target_value" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "stiffness",
                "damping",
                "targetValue"
            })
            public static class Angular {

                @XmlElement(defaultValue = "1.0")
                protected TargetableFloatType stiffness;
                @XmlElement(defaultValue = "0.0")
                protected TargetableFloatType damping;
                @XmlElement(name = "target_value", defaultValue = "0.0")
                protected TargetableFloatType targetValue;

                /**
                 * Gets the value of the stiffness property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public TargetableFloatType getStiffness() {
                    return stiffness;
                }

                /**
                 * Sets the value of the stiffness property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public void setStiffness(TargetableFloatType value) {
                    this.stiffness = value;
                }

                /**
                 * Gets the value of the damping property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public TargetableFloatType getDamping() {
                    return damping;
                }

                /**
                 * Sets the value of the damping property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public void setDamping(TargetableFloatType value) {
                    this.damping = value;
                }

                /**
                 * Gets the value of the targetValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public TargetableFloatType getTargetValue() {
                    return targetValue;
                }

                /**
                 * Sets the value of the targetValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public void setTargetValue(TargetableFloatType value) {
                    this.targetValue = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="stiffness" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
             *         &lt;element name="damping" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
             *         &lt;element name="target_value" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "stiffness",
                "damping",
                "targetValue"
            })
            public static class Linear {

                @XmlElement(defaultValue = "1.0")
                protected TargetableFloatType stiffness;
                @XmlElement(defaultValue = "0.0")
                protected TargetableFloatType damping;
                @XmlElement(name = "target_value", defaultValue = "0.0")
                protected TargetableFloatType targetValue;

                /**
                 * Gets the value of the stiffness property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public TargetableFloatType getStiffness() {
                    return stiffness;
                }

                /**
                 * Sets the value of the stiffness property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public void setStiffness(TargetableFloatType value) {
                    this.stiffness = value;
                }

                /**
                 * Gets the value of the damping property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public TargetableFloatType getDamping() {
                    return damping;
                }

                /**
                 * Sets the value of the damping property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public void setDamping(TargetableFloatType value) {
                    this.damping = value;
                }

                /**
                 * Gets the value of the targetValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public TargetableFloatType getTargetValue() {
                    return targetValue;
                }

                /**
                 * Sets the value of the targetValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TargetableFloatType }
                 *     
                 */
                public void setTargetValue(TargetableFloatType value) {
                    this.targetValue = value;
                }

            }

        }

    }

}
